# Generated by Django 2.1.5 on 2019-02-19 09:41

from django.db import migrations, models
import faces.models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facedetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('encoding', models.TextField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to=faces.models.faces)),
                ('video', models.FileField(blank=True, upload_to=faces.models.video_encoding)),
            ],
        ),
        migrations.DeleteModel(
            name='FaceEncoding',
        ),
    ]
