# Generated by Django 2.1.5 on 2019-02-19 11:47

from django.db import migrations, models
import faces.models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0004_auto_20190219_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedetail',
            name='image',
            field=models.ImageField(blank=True, upload_to=faces.models.faces),
        ),
    ]
