# Generated by Django 2.1.5 on 2019-02-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0005_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='a',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='b',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='c',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='auth_pwd',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='auth_uname',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='d',
        ),
        migrations.AlterField(
            model_name='camera',
            name='ip',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
