# Generated by Django 2.1.5 on 2019-02-22 06:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0007_auto_20190215_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=0, max_length=128, null=True),
        ),
    ]
