# Generated by Django 2.1.5 on 2019-02-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0008_auto_20190222_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(max_length=30),
        ),
    ]
